const Items = [
  {
    id: 1,
    mainImage: "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707379610/Projects/Ui.png",
    img: [
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707372519/Projects/signup.png",
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707372503/Projects/signin.png",
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707372526/Projects/forgot-password.png",
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707372540/Projects/Edit-profile.png",
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707372550/Projects/Search.png",
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707372558/Projects/comment.png",
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707372574/Projects/404.png",
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707372580/Projects/Blog-fromat.png",
    ],
    features: [
      "User registration and login",
      "Authentication using JWT Tokens",
      "Story searching and pagination",
      "CRUD operations (Story create, read, update and delete)",
      "Upload user ımages and story ımages to the server",
      "Liking stories and adding stories to the Reading list",
      "Commenting on the story",
      "Skeleton loading effect",
      "Responsive Design",
      "404 Page and many more.",
    ],
    technologies: [
      "React",
      "React Hooks",
      "React Icons",
      "Axios",
      "CSS",
      "UUID",
      "NodeJS",
      "ExpressJS",
      "MongoDB",
      "Mongoose",
      "Express Asynsc Handler",
      "Json Web Token",
      "Bcryptjs",
      "Nodemailer",
      "Dontenv",
      "Multer",
      "Slugify",
      "Cors",
    ],
    title: "Mern Blog",
    description:
      "Fullstack open source blogging application made with MongoDB, Express, React & Nodejs (MERN)",
    category: "personal",
    liveLink: "https://full-stack-blogs.vercel.app/",
    codeLink: "https://github.com/RajAditya01/FullStack-Blogs?tab=readme-ov-file",
  },

  {
    id: 2,
    mainImage: "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1718987942/Screenshot_2024-06-21_220822_atmqd5.png",
    img: [
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707568969/Projects/Screenshot_2024-02-10_180541_hxktlm.png",
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707568975/Projects/Screenshot_2024-02-10_180324_colcso.png",
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707568972/Projects/Screenshot_2024-02-10_180525_qictaa.png",
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707568965/Projects/Screenshot_2024-02-10_180252_sf67pu.png",
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707626131/Projects/schema_xhug8x.png",
      // ... add more image URLs as needed
    ],
    features: [
      "User Authentication with JWT",
      "Course and Lesson Management",
      "Progress Tracking for Students",
      "Payment Integration with Razorpay",
      "Search Functionality",
      "Instructor Dashboard with Charts and Visualizations",
    ],
    technologies: [
      "React",
      "React Hooks",
      "React Icons",
      "Axios",
      "CSS",
      "UUID",
      "NodeJS",
      "ExpressJS",
      "MongoDB",
      "Mongoose",
      "Express Asynsc Handler",
      "Json Web Token",
      "Bcryptjs",
      "Nodemailer",
      "Dontenv",
      "Multer",
      "Slugify",
      "Cors",
      "Razorpay",

      // ... add more technologies as needed
    ],
    title: "Study Notion",
    description:
      "ED Tech web application developed using the MERN stack for secure user authentication, course management, progress tracking, payment integration, and a feature-rich instructor dashboard.",
    category: "personal",
    liveLink: "https://study-notion-app.example.com/",
    codeLink: "https://github.com/RajAditya01/StudyNotion-An-Online-Education-Platform",
  },

  {
    id: 3,
    mainImage: "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1708609414/voiw7s2dcjua50rgtkpy.png",
    img: [
        "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1708608990/Projects/Screenshot_2024-02-22_190322_ludqfc.png",
        "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1708609008/Projects/Screenshot_2024-02-22_190253_p4kbye.png",
        "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1708839490/Projects/cor7dedcjay8phj2ecqa.png",
        "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1708839515/Projects/pqutamstms9ncmgffhgz.png",
        "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1708839515/Projects/lzi9ncrjgpp6dj3clk3j.png",
        "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1708839489/Projects/r2vod8onbmfbqetfrryz.png",
        "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1708839489/Projects/e1roadm7rx0utl3q2vvu.png",
        // ... add more image URLs as needed
    ],
    features: [
        "User Authentication with JWT",
        "Job Listing and Application Management",
        "Resume Upload and Parsing",
        "Application Tracking System",
        "Search Functionality",
        "Employer Dashboard with Analytics",
    ],
    technologies: [
        "React",
        "Vite",
        "React Hooks",
        "React Icons",
        "Axios",
        "CSS",
        "UUID",
        "NodeJS",
        "ExpressJS",
        "MongoDB",
        "Mongoose",
        "Express Async Handler",
        "Json Web Token",
        "Bcryptjs",
        "cloudnary",
        "cookie-Parser",
        "validator",
        "Dotenv",
        "Express-fileupload",
        "Slugify",
        "Cors",
        
        // ... add more technologies as needed
    ],
    title: "Job Seeking Web App",
    description:
        "A comprehensive job-seeking platform developed using the MERN stack. This web application facilitates user authentication, job listing, application management, resume parsing, and provides both job seekers and employers with feature-rich dashboards.",
    category: "job-seeking",
    liveLink: "https://job-seeking-app.example.com/",
    codeLink: "https://github.com/RajAditya01/MERN-Job-Portal",
},
{
  id: 4,
  mainImage: "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1711713209/Projects/DiagnoTrack_c0qozx.png",
  img: [
    "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1711713209/Projects/DiagnoTrack_c0qozx.png",
    "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1711713209/Projects/DiagnoTrack_c0qozx.png",
    // Add more image URLs as needed
  ],
  features: [
    "Assessment of software and hardware info",
    "Sensor tests",
    "Battery condition assessment",
    "Generation of detailed reports",
  ],
  technologies: [
    "Java",
    "Android",
    // Add more technologies as needed
  ],
  title: "DiagnoTrack",
  description:
    "Mobile diagnostic tool for Android devices developed using Java. It assesses software and hardware info, conducts sensor tests, evaluates battery conditions, and generates detailed reports for in-depth device performance analysis.",
    category: "personal",
  codeLink: "https://github.com/RajAditya01/AndroidStudioProjects/tree/main/MegaToolsApp",
},

{
  id: 5,
  mainImage: "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1711713727/NoteNationNoteNation_jkkorc.png",
  img: [
    "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1711713727/NoteNationNoteNation_jkkorc.png",
    "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1711713727/NoteNationNoteNation_jkkorc.png",
    // Add more image URLs as needed
  ],
  features: [
    "User-friendly note creation",
    "Organizing and managing notes efficiently",
  ],
  technologies: [
    "Java",
    "JSP-Servlet",
    "Bootstrap",
    "MySQL",
    "Apache Tomcat",
    // Add more technologies as needed
  ],
  title: "NoteNation",
  description:
    "NoteNation is a note-taking dynamic website developed using Java JSP-Servlet, Bootstrap, and MySQL, hosted on Apache Tomcat. It provides a user-friendly platform for creating, organizing, and managing notes efficiently.",
    category: "personal",
  codeLink: "https://github.com/RajAditya01/Advance-java/tree/main/NoteNation",
},

{
  id: 6,
  mainImage: "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1714878822/Screenshot_2024-05-04_180245_nlgsia.png",
  img: [
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1714878805/Screenshot_2024-05-04_164630_m260xk.png",
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1714878843/Screenshot_2024-05-04_164645_vzlinn.png",
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1714878939/Screenshot_2024-05-05_084509_yvz4bh.png",
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1714878954/Screenshot_2024-05-05_084443_cuu7vt.png",
  ],
  features: [
      "User Registration and Login",
      "Authentication using JWT Tokens",
      "Property Searching and Filtering",
      "Pagination for Property Listings",
      "CRUD operations (Property create, read, update, and delete)",
      "Uploading Property Images to the Server",
      "Favoriting Properties and Creating a Wishlist",
      "Booking Property Tours and Appointments",
      "Real-time Chat between Tenants and Landlords",
      "Responsive Design for all Devices"
  ],
  technologies: [
      "React.js",
      "React Hooks",
      "React Router",
      "axios",
      "CSS",
      "Material-UI",
      "Mapbox",
      "Socket.io",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Mongoose",
      "jsonwebtoken",
      "Bcrypt.js",
      "Nodemailer"
  ],
  title: "Real RentalHub",
  description: "Real RentalHub is a full-stack application designed to revolutionize the way people find and list properties for rent. With a sleek and intuitive interface, it provides users with a seamless experience for discovering, renting, and managing rental properties.",
  category: "real-estate",
  liveLink: "",
  codeLink: "https://github.com/RajAditya01/RealRentalHub"
},

{
  id: 7,
  mainImage: "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1718987627/Screenshot_2024-06-21_220323_azd3p6.png",
  img: [
    "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1717585050/Projects/Screenshot_2024-06-05_162606_kg6fgy.png",
    "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1718438250/Screenshot_2024-06-15_132414_jqbb4b.png",
    "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1718439319/Screenshot_2024-06-15_134419_atqxc6.png",
    "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1718439318/Screenshot_2024-06-15_134234_z6m5m6.png",
    "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1718439318/Screenshot_2024-06-15_134148_lfngpp.png",
    "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1718439318/Screenshot_2024-06-15_134208_curyvz.png",
  ],
  features: [
    "User registration and login",
    "Authentication using JWT Tokens",
    "Product browsing and filtering",
    "Product details page with images and descriptions",
    "Adding products to the shopping cart",
    "Managing shopping cart items (update quantity, remove items)",
    "Checkout process with order summary and payment integration",
    "Real-time order tracking",
    "Responsive design for all devices",
  ],
  technologies: [
    "React.js",
    "Next.js",
    "TypeScript",
    "Tailwind CSS",
    "axios",
    "Supabase",
  ],
  title: "E-commerce Website",
  description: "Full-stack e-commerce platform built from scratch using ReactJS, Next.js with TypeScript, Tailwind CSS, and Supabase.",
  category: "personal",
  liveLink: "https://e-commerce-full-stack-lac.vercel.app/",
  codeLink: "https://github.com/RajAditya01/E-commerce-Full-Stack",
},

{
  id: 8,
  mainImage: "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1718987222/Screenshot_2024-06-21_215643_q2oehp.png",
  img: [
    "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1717585473/Projects/Screenshot_2024-05-25_113903_vdh5cr.png",
    "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1717585469/Projects/Screenshot_2024-05-25_114430_t3wcky.png",
    "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1717585469/Projects/Screenshot_2024-05-25_114500_exodde.png",
    "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1717585300/Projects/Screenshot_2024-05-25_114430_lfxkzm.png",
  ],
  features: [
    "Real-time messaging: Users can chat with each other in real-time.",
    "User authentication: Secure user authentication system implemented for login and registration.",
    "Responsive design: The application is optimized for various screen sizes and devices.",
    "MongoDB database: Data is stored and managed using MongoDB, a popular NoSQL database solution.",
  ],
  technologies: [
    "Socket.io",
    "MongoDB",
    "Express.js",
    "React.js",
    "Node.js",
    "DaisyUI",
    "Tailwind CSS",
  ],
  title: "ChatterBox",
  description: "ChatterBox is a real-time chat application built using Socket.io and the MERN stack (MongoDB, Express.js, React.js, Node.js). It utilizes DaisyUI and Tailwind CSS for a sleek and responsive user interface.",
  category: "personal",
  liveLink: "https://chatterbox-app.vercel.app/",
  codeLink: "https://github.com/RajAditya01/ChatterBox",
},

{
  id: 9,
  mainImage: "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1718986803/Screenshot_2024-06-21_214943_kczj2i.png",
  img: [
    "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1718986439/Screenshot_2024-06-21_214130_q2m9va.png",
    "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1718986468/Screenshot_2024-06-21_214150_wburr6.png",
  ],
  features: [
    "High-Quality Video Calls",
    "Screen Sharing",
    "Chat",
    "Group Calls",
    "End-to-End Encryption",
  ],
  technologies: [
    "React",
    "Redux",
    "ZEGOCLOUD SDK",
    "MongoDB (optional for user management)",
  ],
  title: "VideoCall App",
  description: "VideoCall App is a user-friendly video communication application built with React and powered by ZEGOCLOUD. It supports high-quality video calls, real-time chat, and screen sharing functionalities.",
  category: "personal",
  liveLink: "https://videocall-app-tau.vercel.app/",
  codeLink: "https://github.com/RajAditya01/videocall-app",
},
];

export default Items;
