const Items = [
  {
    id: 1,
    mainImage: "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707379610/Projects/Ui.png",
    img: [
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707372519/Projects/signup.png",
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707372503/Projects/signin.png",
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707372526/Projects/forgot-password.png",
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707372540/Projects/Edit-profile.png",
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707372550/Projects/Search.png",
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707372558/Projects/comment.png",
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707372574/Projects/404.png",
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707372580/Projects/Blog-fromat.png",
    ],
    features: [
      "User registration and login",
      "Authentication using JWT Tokens",
      "Story searching and pagination",
      "CRUD operations (Story create, read, update and delete)",
      "Upload user ımages and story ımages to the server",
      "Liking stories and adding stories to the Reading list",
      "Commenting on the story",
      "Skeleton loading effect",
      "Responsive Design",
      "404 Page and many more.",
    ],
    technologies: [
      "React",
      "React Hooks",
      "React Icons",
      "Axios",
      "CSS",
      "UUID",
      "NodeJS",
      "ExpressJS",
      "MongoDB",
      "Mongoose",
      "Express Asynsc Handler",
      "Json Web Token",
      "Bcryptjs",
      "Nodemailer",
      "Dontenv",
      "Multer",
      "Slugify",
      "Cors",
    ],
    title: "Mern Blog",
    description:
      "Fullstack open source blogging application made with MongoDB, Express, React & Nodejs (MERN)",
    category: "personal",
    liveLink: "https://full-stack-blogs.vercel.app/",
    codeLink: "https://github.com/RajAditya01/FullStack-Blogs?tab=readme-ov-file",
  },

  {
    id: 2,
    mainImage: "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707568969/Projects/Screenshot_2024-02-10_180541_hxktlm.png",
    img: [
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707568969/Projects/Screenshot_2024-02-10_180541_hxktlm.png",
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707568969/Projects/Screenshot_2024-02-10_180541_hxktlm.png",
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707568972/Projects/Screenshot_2024-02-10_180525_qictaa.png",
      "https://res.cloudinary.com/ddjk9ccx5/image/upload/v1707568975/Projects/Screenshot_2024-02-10_180324_colcso.pnghttps://res.cloudinary.com/ddjk9ccx5/image/upload/v1707568975/Projects/Screenshot_2024-02-10_180324_colcso.png",
      // ... add more image URLs as needed
    ],
    features: [
      "User Authentication with JWT",
      "Course and Lesson Management",
      "Progress Tracking for Students",
      "Payment Integration with Razorpay",
      "Search Functionality",
      "Instructor Dashboard with Charts and Visualizations",
    ],
    technologies: [
      "React",
      "React Hooks",
      "React Icons",
      "Axios",
      "CSS",
      "UUID",
      "NodeJS",
      "ExpressJS",
      "MongoDB",
      "Mongoose",
      "Express Asynsc Handler",
      "Json Web Token",
      "Bcryptjs",
      "Nodemailer",
      "Dontenv",
      "Multer",
      "Slugify",
      "Cors",
      "Razorpay",

      // ... add more technologies as needed
    ],
    title: "Study Notion",
    description:
      "ED Tech web application developed using the MERN stack for secure user authentication, course management, progress tracking, payment integration, and a feature-rich instructor dashboard.",
    category: "educational",
    liveLink: "https://study-notion-app.example.com/",
    codeLink: "",
  },

];

export default Items;
